### ISSUE TITLE
Minimal latency with a WebSocket raw H264 stream ?

### ISSUE THREAD

**Issue by Serveurperso** [samirkumardas/jmuxer#23]
Hello,

What about the minimal latency of a player implementation if I use a WebSocket raw H264 stream ?
With Broadway it's very low, but it consume more CPU power than a native HTML5 player.

Pascal

**Comment by samirkumardas** [comment]
Obviously latency is not greater than Broadway, moreover Broadway only support baseline profile and no audio.
 
At least I had not got any noticeable difference than Broadway.

**Comment by Serveurperso** [comment]
Same latency as Broadway? it's f-cking amazing! We use Broadway to make a non lucrative universal robotics remote control (https://www.vigibot.com -> zero ads) I begin testing but I get a javascript error similar to "can't find the Console object" when I enable debug: true...
I need to push NAL unit one by one to jmuxer? On our system 1 websocket event = 1 NAL Unit. it's good? what is the tuning for minimum latency?

**Comment by samirkumardas** [comment]
It is not necessary to feed single NAL unit, you can feed a chunk of h264 data  i.e multiple number of NALUs 

Basically it is better to put a chunk because player will not start until it get key frame i.e IDR

**Comment by Serveurperso** [comment]
The system always start on an IDR NALU.
SPS and PPS NALU are remembered by server and re-injected before IDR if necessary
I can switch multiple robot video in realtime, latency of each network & software parts are displayed on client... I just need a very low latency H264 player on client side:)

**Comment by Serveurperso** [comment]
Latency is incomparable with Broadway for robot piloting.
Each NAL unit send must be immediately decoded on client side (after the first IDR of course)

**Comment by samirkumardas** [comment]
was this your comment  Or question? Have you able to run your stream?

**Comment by Serveurperso** [comment]
Yes I just say this because I tested your example code and if you don't send and decode NALU ONE by ONE, you must add a buffering on transmitter side and schedule the playback in the future on the browser side.

I do more test now inside my robotics code.

**Comment by Serveurperso** [comment]
How to use debug mode ?
I always get : TypeError: 'error' called on an object that does not implement interface Console.

**Comment by Serveurperso** [comment]
On your own page https://samirkumardas.github.io/jmuxer/ I get :
TypeError: 'log' called on an object that does not implement interface Console.
It work on my Chrome Mobile but not on a old corporate firefox 45.7.0

**Comment by Serveurperso** [comment]
I'm stuck because I can't debug and there is no example or documentation:'(

**Comment by samirkumardas** [comment]
hmm, could be old browser compatibility issue. I don't have ff v45 right now. 
You can continue with chrome now. I will check in this weekend when I get some time.

**Comment by Serveurperso** [comment]
Broadway (and my robotics website) work with any browser even firefox v45 and EDGE and all mobile !
I can't get https://samirkumardas.github.io/jmuxer working even with last firefox, chrome is OK
I can't work with a non perfectly compatible video...

**Comment by samirkumardas** [comment]
Good, this is your choice.

By the way, what did you mean by last firefox? Current version of firefox is 66 which is far updated than you are using v45

**Comment by Serveurperso** [comment]
Yes Firefox 66.0.3 do not work with your demo page, it's a perpetual loading

**Comment by samirkumardas** [comment]
It is working well in FF  66.0.3.  You may need clicking the play button sometimes depending on browser setting

**Comment by Serveurperso** [comment]
lol i know. it do not work
